### ISSUE TITLE
Make postcss a peerDependency

### ISSUE THREAD

**Issue by necolas** [postcss/postcss-bem-linter#42]
…rather than installing and using another version of postcss inside this plugin

**Comment by vanesyan** [comment]
`peerDependencies` are being deprecated in the next major release of `npm`. See: npm/npm#6565

**Comment by necolas** [comment]
auto-install is being deprecated

**Comment by ai** [comment]
@necolas PostCSS plugin anyway need a PostCSS dependency for helpers and `postcss.plugin` builder.

**Comment by ai** [comment]
Also @MoOx was agains `peerDependency` because npm team had a plans to remove it and ask to use in-app tests.

**Comment by necolas** [comment]
Ugh. I just need to move to css-in-js :)

**Comment by ai** [comment]
@necolas what do you mean? :)

**Comment by MoOx** [comment]
He mean something like this https://github.com/petehunt/jsxstyle
Style as JS object (so no .css files anymore, so no need for postcss nor a linter).

@necolas since if postcss is declared as a dep and user will have it at their own level too, it won't be installed twice, so I guess you can just close this issue :)

**Comment by ai** [comment]
I didn't understand for dependencies are relevant to css on js :-)
